export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    ME: "/auth/me",
    PROFILE: "/auth/profile",
    PASSWORD: "/auth/password",
  },
  VEHICLES: {
    BASE: "/vehicles",
    BY_ID: (id) => `/vehicles/${id}`,
    STATUS: (id) => `/vehicles/${id}/status`,
    IMAGES: (id) => `/vehicles/${id}/images`,
  },
  JOBS: {
    BASE: "/jobs",
    BY_ID: (id) => `/jobs/${id}`,
    STATUS: (id) => `/jobs/${id}/status`,
    ASSIGN: (id) => `/jobs/${id}/assign`,
    NOTES: (id) => `/jobs/${id}/notes`,
    NOTE_AT: (id, idx) => `/jobs/${id}/notes/${idx}`,
    PARTS: (id) => `/jobs/${id}/parts`,
    PART_AT: (id, idx) => `/jobs/${id}/parts/${idx}`,
    STATS: "/jobs/stats",
  },
  FC: {
    BASE: "/fc",
    BY_ID: (id) => `/fc/${id}`,
    RESULT: (id) => `/fc/${id}/result`,
    EXPIRING: "/fc/expiring",
  },
  INVOICES: {
    BASE: "/invoices",
    BY_ID: (id) => `/invoices/${id}`,
    MARK_PAID: (id) => `/invoices/${id}/mark-paid`,
    PARTIAL_PAYMENT: (id) => `/invoices/${id}/partial-payment`,
    CANCEL: (id) => `/invoices/${id}/cancel`,
    REVENUE_SUMMARY: "/invoices/revenue-summary",
  },
  INVENTORY: {
    BASE: "/inventory",
    BY_ID: (id) => `/inventory/${id}`,
    RESTOCK: (id) => `/inventory/${id}/restock`,
    LOW_STOCK: "/inventory/low-stock",
  },
  EMPLOYEES: {
    BASE: "/employees",
    BY_ID: (id) => `/employees/${id}`,
    STATUS: (id) => `/employees/${id}/status`,
    STATS: (id) => `/employees/${id}/stats`,
  },
  CUSTOMERS: {
    BASE: "/customers",
    BY_PHONE: (phone) => `/customers/${phone}`,
    VEHICLES: (phone) => `/customers/${phone}/vehicles`,
  },
  DASHBOARD: {
    SUMMARY: "/dashboard/summary",
    ACTIVITY: "/dashboard/activity",
    STATUS_DIST: "/dashboard/status-distribution",
    MONTHLY_REVENUE: "/dashboard/monthly-revenue",
    MY_JOBS: "/dashboard/my-jobs",
  },
};
